### ISSUE TITLE
Profile picture and social icons scaling issue on Gmail

### ISSUE THREAD

**Issue by nareddyt** [antonreshetov/mysigmail#2]
Awesome work on this project, its highly customization and simple to use!

Here is a **bug report** specifically for gmail. Not sure if it's an issue with Gmail or this project.

Let me know if you want me to look into this. I just don't know where to start.

### Issue

On gmail, the scale of the profile picture and social icons change after saving the signature.

Here is my signature as soon as I copy it in:

![image](https://user-images.githubusercontent.com/11142171/50705083-9caf1680-1027-11e9-91cf-eb820bf31782.png)

However, once I save the settings on this page and view it again, the signature changes to this:

![image](https://user-images.githubusercontent.com/11142171/50705112-c0725c80-1027-11e9-9884-a77b8059efe0.png)

This shows up in the signature when sending emails as well.

### Reproduction Data

Here is the data file I exported:

```json
{
   "id":1546625462061,
   "name":"Untitled project",
   "template":"EmailTemplate1",
   "basic":{
      "image":{
         "base64":"",
         "link":"https://avatars0.githubusercontent.com/u/11142171?s=460&v=4"
      },
      "fields":[
         {
            "name":"Full name",
            "type":"text",
            "value":"Tejasvi (Teju) Nareddy",
            "id":"jb6xb0ulxyg"
         },
         {
            "name":"Job title",
            "type":"text",
            "value":"Student",
            "id":"04gxlferuffb"
         },
         {
            "name":"Company",
            "type":"text",
            "value":"Georgia Institute of Technology",
            "id":"57zkiswirx8"
         },
         {
            "name":"Website",
            "type":"link",
            "value":"www.tejunareddy.com",
            "id":"x5u281reqx"
         },
         {
            "name":"Email",
            "type":"email",
            "value":"tejunareddy@gmail.com",
            "id":"8p7eet8mvu"
         },
         {
            "name":"Phone",
            "type":"text",
            "value":"508-410-0364",
            "id":"0m8c26uwwqjq"
         }
      ]
   },
   "options":{
      "avatar":{
         "size":133,
         "roundness":5
      },
      "font":{
         "size":12,
         "family":"Verdana, sans-serif"
      },
      "color":{
         "main":"#409eff",
         "secondary":"#409EFF"
      },
      "separator":"at"
   },
   "addons":{

   },
   "socials":{
      "installed":[
         {
            "name":"Linkedin",
            "link":"www.linkedin.com/in/tejasvinareddyteju",
            "icon":"linkedin"
         },
         {
            "name":"GitHub",
            "link":"https://github.com/nareddyt",
            "icon":"github"
         }
      ]
   }
}
```

**Comment by nareddyt** [comment]
I was able to resolve the issue with the profile picture by changing the URL to reference a 133x133 picture. Note this matches the `options.avatar.size` setting in the json above.

https://avatars0.githubusercontent.com/u/11142171?s=133&v=4

**However, the social icons are still not scaled properly!** Any thoughts on this?

**Comment by antonreshetov** [comment]
Hi, @nareddyt

Tell me if the problem persists when you send an email with this signature. I assume that style changes occur in the gmail application at the time the signature is viewed.

If insert the HTML code of the signature, for example https://jsfiddle.net/antonreshetov/ospw1809/1/ , the signature looks exactly as in the generator

**Comment by nareddyt** [comment]
Huh interesting. Yes, it occurs when sending an email as well (the boxes are bigger than normal). It also seems like the social media images don't load from S3...

![image](https://user-images.githubusercontent.com/11142171/50706547-2b259700-102c-11e9-9c9c-1f25bf424e09.png)

Like you said, I'm assuming these are gmail-specific issues. Do you think this is worth investigating? I can use the signature without the social media icons, and it would still look great!

**Comment by antonreshetov** [comment]
I read that the gmail client can only be inserted as a **copy as select**. I may not have found another solution.

**Comment by nareddyt** [comment]
Perhaps the social media images need to be hosted in S3 as 12x12 jpgs? Changing the size of the image for the profile picture fixed scaling issues with it. This could be similar?

**Comment by antonreshetov** [comment]
@nareddyt 
I think I found the reason, gmail adds its proxy address to the links to the icons, if you click on this link, we get 404
`https://ci4.googleusercontent.com/proxy/x_EZnduv8XeoL4bDdgAfs7OuWTMxO6qn5a0_TWP22Dj0J65rvh8bGEaKoSJ7oKFSACQvjnUd1s12mGRCZVzyyzJZwrC_IS3wjuOl4O4ZCw=s0-d-e1-ft#https://s3.eu-central-1.amazonaws.com/mysigmail/icons/vk.svg`

**Comment by nareddyt** [comment]
Wow, didn't know that. I wonder why it works for the profile picture...

https://ci4.googleusercontent.com/proxy/cluVg2lB8ALYIZUy7Z7762a5fggTl31xHyvsgEFVTioqLLOl-ulURO9sgNBRNcLtc-Pf5KzIrYz6kyTWCiNtmVT2V0JZ8w6HxjQ=s0-d-e1-ft#https://avatars0.githubusercontent.com/u/11142171?s=135

I did some research, and [this StackOverflow post](https://stackoverflow.com/questions/20903967/gmails-new-image-caching-is-breaking-image-links-in-newsletter) might help! Here are some notable quotes from the answers:

> Rename your images to something else with png, jpg or gif extensions only.

> your image must include png, jpg or gif as an extension.

If you'd like, I can try hosting the social media icons at a different URL as jpgs and checking if it works better. I probably won't be able to do this until Monday though!

**Comment by nareddyt** [comment]
Works now! Thanks for the quick fix @antonreshetov 

![image](https://user-images.githubusercontent.com/11142171/50725850-814d1580-10d2-11e9-84e5-349b80d13cbd.png)

**Comment by nareddyt** [comment]
Closed because it was fixed in #7

**Comment by iam-rocketman** [comment]
I think this issue still exist, when i copy as select to gmail, the social icons go big. 
<img width="478" alt="screen shot 2019-02-12 at 10 28 25 am" src="https://user-images.githubusercontent.com/768793/52612899-aabb4700-2eb1-11e9-8fee-94ee39f8812c.png">

Above issue is what i am facing, turnaround for this fix to use the backspace twic and icon comes to normal size.
